package default_package;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.4
 * 2024-11-03T17:02:12.111Z
 * Generated source version: 3.6.4
 *
 */
@WebService(targetNamespace = "http://default_package/", name = "MathUtility")
@XmlSeeAlso({ObjectFactory.class})
public interface MathUtility {

    @WebMethod
    @RequestWrapper(localName = "addIntegers", targetNamespace = "http://default_package/", className = "default_package.AddIntegers")
    @ResponseWrapper(localName = "addIntegersResponse", targetNamespace = "http://default_package/", className = "default_package.AddIntegersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int addIntegers(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "factorial", targetNamespace = "http://default_package/", className = "default_package.Factorial")
    @ResponseWrapper(localName = "factorialResponse", targetNamespace = "http://default_package/", className = "default_package.FactorialResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int factorial(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "queryDatabase", targetNamespace = "http://default_package/", className = "default_package.QueryDatabase")
    @ResponseWrapper(localName = "queryDatabaseResponse", targetNamespace = "http://default_package/", className = "default_package.QueryDatabaseResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> queryDatabase(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
