
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package default_package;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.4
 * 2024-11-03T17:02:12.077Z
 * Generated source version: 3.6.4
 *
 */

@javax.jws.WebService(
                      serviceName = "MathUtilityService",
                      portName = "MathUtilityPort",
                      targetNamespace = "http://default_package/",
                      wsdlLocation = "http://localhost:8080/ProjetoComputacao/services/MathUtilityPort?wsdl",
                      endpointInterface = "default_package.MathUtility")

public class MathUtilityPortImpl implements MathUtility {

    private static final Logger LOG = Logger.getLogger(MathUtilityPortImpl.class.getName());

    /* (non-Javadoc)
     * @see default_package.MathUtility#addIntegers(int arg0, int arg1)*
     */
    public int addIntegers(int arg0, int arg1) {
        LOG.info("Executing operation addIntegers");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = -1553716779;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.MathUtility#factorial(int arg0)*
     */
    public int factorial(int arg0) {
        LOG.info("Executing operation factorial");
        System.out.println(arg0);
        try {
            int _return = 917052818;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.MathUtility#queryDatabase(java.lang.String arg0)*
     */
    public java.util.List<java.lang.String> queryDatabase(java.lang.String arg0) {
        LOG.info("Executing operation queryDatabase");
        System.out.println(arg0);
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal-1994568172";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
