
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package default_package;

import java.util.List;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.sql.Timestamp;

/**
 * This class was generated by Apache CXF 3.6.4
 * 2024-12-14T15:31:46.069Z
 * Generated source version: 3.6.4
 *
 */

@javax.jws.WebService(
                      serviceName = "MathUtilityService",
                      portName = "MathUtilityPort",
                      targetNamespace = "http://default_package/",
                      wsdlLocation = "http://localhost:8080/ProjetoComputacao/services/MathUtilityPort?wsdl",
                      endpointInterface = "default_package.MathUtility")

public class MathUtilityPortImpl implements MathUtility {

    private static final Logger LOG = Logger.getLogger(MathUtilityPortImpl.class.getName());

    /* (non-Javadoc)
     * @see default_package.MathUtility#addIntegers(int arg0, int arg1)*
     */
    public int addIntegers(int arg0, int arg1) {
        LOG.info("Executing operation addIntegers");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = 148535944;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    public java.util.List<java.lang.String> listarClinicas(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation listarClinicas");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal1466544289";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	public java.util.List<java.lang.String> listarConsultasPaciente(int arg0) {
        LOG.info("Executing operation listarConsultasPaciente");
        System.out.println(arg0);
        try {
        	java.util.List<java.util.List<java.lang.String>> _return = new java.util.List<java.util.List<java.lang.String>>();
            default_package.Consulta _returnVal1 = new default_package.Consulta();
            _returnVal1.setData("Data1496182221");
            _returnVal1.setMedico("Medico220777365");
            _returnVal1.setMoradaClinica("MoradaClinica-817864215");
            _returnVal1.setNomeClinica("NomeClinica-1397789423");
            _returnVal1.setSintomas("Sintomas-1592560678");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	public java.util.List<java.lang.String> listarClinicas(java.lang.String arg0, Timestamp arg1) {
        LOG.info("Executing operation listarClinicas");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal1055868944";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	public int getIdUsuario(java.lang.String arg0) {
        LOG.info("Executing operation getIdUsuario");
        System.out.println(arg0);
        try {
            int _return = -1675309953;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	public int getIdUsuario(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation getIdUsuario");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = 1420816064;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	public boolean criarPaciente(java.lang.String arg0, java.lang.String arg1, int arg2) {
        LOG.info("Executing operation criarPaciente");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	public boolean marcarConsulta(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, int arg4) {
        LOG.info("Executing operation marcarConsulta");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	public int obterIdUtilizador(java.lang.String arg0) {
        LOG.info("Executing operation obterIdUtilizador");
        System.out.println(arg0);
        try {
            int _return = 560746252;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	/* (non-Javadoc)
     * @see default_package.MathUtility#factorial(int arg0)*
     */
    public int factorial(int arg0) {
        LOG.info("Executing operation factorial");
        System.out.println(arg0);
        try {
            int _return = -1791130728;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	public boolean cancelarConsultaPorUsuario(int arg0, java.lang.String arg1) {
        LOG.info("Executing operation cancelarConsultaPorUsuario");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	public boolean registarUtilizador(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation registarUtilizador");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	public boolean loginUtilizador(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation loginUtilizador");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	public boolean registarUtilizador() {
        LOG.info("Executing operation registarUtilizador");
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	public java.util.List<java.lang.String> queryDatabase(java.lang.String arg0) {
        LOG.info("Executing operation queryDatabase");
        System.out.println(arg0);
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal-548189752";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	public java.util.List<java.lang.String> queryAuthServerTest() {
        LOG.info("Executing operation queryAuthServerTest");
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal223241950";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }


}
