package default_package;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.sql.Timestamp;
import java.util.List;

/**
 * This class was generated by Apache CXF 3.6.4
 * 2024-12-14T15:31:46.080Z
 * Generated source version: 3.6.4
 *
 */
@WebService(targetNamespace = "http://default_package/", name = "MathUtility")
@XmlSeeAlso({ObjectFactory.class})
public interface MathUtility {

    @WebMethod
    @RequestWrapper(localName = "addIntegers", targetNamespace = "http://default_package/", className = "default_package.AddIntegers")
    @ResponseWrapper(localName = "addIntegersResponse", targetNamespace = "http://default_package/", className = "default_package.AddIntegersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int addIntegers(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
    
    

	@WebMethod
    @RequestWrapper(localName = "listarClinicas", targetNamespace = "http://default_package/", className = "default_package.ListarClinicas")
    @ResponseWrapper(localName = "listarClinicasResponse", targetNamespace = "http://default_package/", className = "default_package.ListarClinicasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> listarClinicas(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );




//	@WebMethod
//    @RequestWrapper(localName = "listarConsultasPaciente", targetNamespace = "http://default_package/", className = "default_package.ListarConsultasPaciente")
//    @ResponseWrapper(localName = "listarConsultasPacienteResponse", targetNamespace = "http://default_package/", className = "default_package.ListarConsultasPacienteResponse")
//    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
	@RequestWrapper(localName = "listarConsultasPaciente", targetNamespace = "http://default_package/", className = "default_package.ListarConsultasPaciente")
	@ResponseWrapper(localName = "listarConsultasPacienteResponse", targetNamespace = "http://default_package/", className = "default_package.ListarConsultasPacienteResponse")
	@WebResult(name = "return", targetNamespace = "")
	public java.util.List<java.lang.String> listarConsultasPaciente(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );



	@WebMethod
    @RequestWrapper(localName = "criarPaciente", targetNamespace = "http://default_package/", className = "default_package.CriarPaciente")
    @ResponseWrapper(localName = "criarPacienteResponse", targetNamespace = "http://default_package/", className = "default_package.CriarPacienteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean criarPaciente(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

	@WebMethod
    @RequestWrapper(localName = "marcarConsulta", targetNamespace = "http://default_package/", className = "default_package.MarcarConsulta")
    @ResponseWrapper(localName = "marcarConsultaResponse", targetNamespace = "http://default_package/", className = "default_package.MarcarConsultaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean marcarConsulta(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4
    );



	@WebMethod
    @RequestWrapper(localName = "obterIdUtilizador", targetNamespace = "http://default_package/", className = "default_package.ObterIdUtilizador")
    @ResponseWrapper(localName = "obterIdUtilizadorResponse", targetNamespace = "http://default_package/", className = "default_package.ObterIdUtilizadorResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int obterIdUtilizador(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

	@WebMethod
    @RequestWrapper(localName = "factorial", targetNamespace = "http://default_package/", className = "default_package.Factorial")
    @ResponseWrapper(localName = "factorialResponse", targetNamespace = "http://default_package/", className = "default_package.FactorialResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int factorial(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

	@WebMethod
    @RequestWrapper(localName = "cancelarConsultaPorUsuario", targetNamespace = "http://default_package/", className = "default_package.CancelarConsultaPorUsuario")
    @ResponseWrapper(localName = "cancelarConsultaPorUsuarioResponse", targetNamespace = "http://default_package/", className = "default_package.CancelarConsultaPorUsuarioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean cancelarConsultaPorUsuario(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );



	@WebMethod
    @RequestWrapper(localName = "registarUtilizador", targetNamespace = "http://default_package/", className = "default_package.RegistarUtilizador")
    @ResponseWrapper(localName = "registarUtilizadorResponse", targetNamespace = "http://default_package/", className = "default_package.RegistarUtilizadorResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean registarUtilizador(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );


    
	@WebMethod
    @RequestWrapper(localName = "loginUtilizador", targetNamespace = "http://default_package/", className = "default_package.LoginUtilizador")
    @ResponseWrapper(localName = "loginUtilizadorResponse", targetNamespace = "http://default_package/", className = "default_package.LoginUtilizadorResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean loginUtilizador(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

	@WebMethod
    @RequestWrapper(localName = "queryDatabase", targetNamespace = "http://default_package/", className = "default_package.QueryDatabase")
    @ResponseWrapper(localName = "queryDatabaseResponse", targetNamespace = "http://default_package/", className = "default_package.QueryDatabaseResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> queryDatabase(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

	@WebMethod
    @RequestWrapper(localName = "queryAuthServerTest", targetNamespace = "http://default_package/", className = "default_package.QueryAuthServerTest")
    @ResponseWrapper(localName = "queryAuthServerTestResponse", targetNamespace = "http://default_package/", className = "default_package.QueryAuthServerTestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> queryAuthServerTest()
;
}
