package default_package;
import java.util.List;
import java.util.Scanner;

import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;

import default_package.MathUtility;


public class MathConsumer {

    public static void main(String[] args) {

        JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();        

        // Use the URL defined in the soap address portion of the WSDL
        factory.setAddress("http://localhost:8080/ProjetoComputacao/services/MathUtilityPort"); 
       
        // Utilize the class which was auto-generated by Apache CXF wsdl2java
        factory.setServiceClass(MathUtility.class);        

        Object client = factory.create();

        try {        
    
            // Call the Web Service to perform an operation
            int response = ((MathUtility)client).factorial(5);    
        
            System.out.println(response);    
            int response2 = ((MathUtility)client).addIntegers(5,2);    
            
            
            
            System.out.println(response2); 
            
           
            
            Scanner myObj = new Scanner(System.in);
            System.out.println("Por favor, forneça uma query!");
            String query = myObj.nextLine();
            
            List<String> results = ((MathUtility)client).queryDatabase(query);
            
            for (String result : results) {
                System.out.println(result);
            }

            
        
          } catch (SecurityException e) {

            e.printStackTrace();

          } catch (IllegalArgumentException e) {

            e.printStackTrace();

          }        
    }
}