
package defaultnamespace.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.4
 * Wed Nov 13 02:12:06 WET 2024
 * Generated source version: 3.6.4
 */

@XmlRootElement(name = "registarUtilizador", namespace = "http://default_package/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "registarUtilizador", namespace = "http://default_package/")

public class RegistarUtilizador {


}

